------ Drop tables if already exists --------------------
drop table [STG].[UM_DATA];
drop table [STG].[UM_DATES];
drop table [STG].[UM_HOURS];
drop table [STG].[UM_OPS_HIEARARCHY];
drop table [STG].[UM_OPS_HIEARARCHY_DESCR_FILE];
drop table [STG].[UM_ATTRIBUTES];
drop table [ODS].[D_STORE];

-------------------- [STG].[UM_DATA] -------------
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[UM_DATA](
	[C_UNIT_NO] [varchar](20) NOT NULL,
	[C_OWNER] [varchar](1) NULL,
	[C_UM_STATUS] [varchar](1) NULL,
	[C_CONCEPT_CD] [varchar](5) NULL,
	[COUNTRY] [varchar](3) NULL,
	[ADDRESS1] [varchar](200) NULL,
	[ADDRESS2] [varchar](100) NULL,
	[ADDRESS3] [varchar](100) NULL,
	[CITY] [varchar](20) NULL,
	[STATE] [varchar](10) NULL,
	[POSTAL] [varchar](20) NULL,
	[C_UM_DMA_CD] [varchar](10) NULL,
	[C_LATITUDE] [varchar](100) NULL,
	[C_LONGITUDE] [varchar](100) NULL,
	[DT_TIMER] [varchar](10) NULL,
	[REGIONAL_AREA] [varchar](10) NULL,
	[PLAYGROUND] [varchar](1) NULL,
	[C_SITETYPECD] [varchar](5) NULL,
	[C_SOFTWARE_AGMT] [varchar](1) NULL,
	[C_POSSUPPORTED] [varchar](10) NULL,
	[C_PROGTYPEPOLLED] [varchar](20) NULL,
	[C_POSSUPVNDR] [varchar](100) NULL,
	[C_TLOG] [varchar](10) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL
) ON [PRIMARY]
GO

------------------ Create table [STG].[UM_DATES] -------
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[UM_DATES](
	[C_UNIT_NO] [varchar](20) NOT NULL,
	[C_EVENTCD] [varchar](5) NOT NULL,
	[DESCR] [varchar](100) NOT NULL,
	[EFFDT] [varchar](50) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL
) ON [PRIMARY]
GO
-----------------Create table  [STG].[UM_HOURS] ----------------
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[UM_HOURS](
	[RESTAURANT] [varchar](20) NOT NULL,
	[NAME] [varchar](100) NOT NULL,
	[ADDRESS] [varchar](200) NULL,
	[CITY] [varchar](20) NULL,
	[STATE] [varchar](10) NULL,
	[ZIPCODE] [varchar](20) NULL,
	[COUNTRY] [varchar](3) NULL,
	[PHONE] [varchar](10) NULL,
	[CONCEPT] [varchar](5) NULL,
	[LATITUDE] [varchar](100) NULL,
	[LONGITUDE] [varchar](100) NULL,
	[RANK_DESCR] [varchar](10) NULL,
	[AP_CHK_VALID] [varchar](10) NULL,
	[MONDAY_24_HOUR] [varchar](1) NULL,
	[MONDAY_START] [varchar](20) NULL,
	[MONDAY_END] [varchar](20) NULL,
	[MONDAY_CLOSE] [varchar](1) NULL,
	[TUESDAY_24_HOUR] [varchar](1) NULL,
	[TUESDAY_START] [varchar](20) NULL,
	[TUESDAY_END] [varchar](20) NULL,
	[TUESDAY_CLOSE] [varchar](1) NULL,
	[WEDNESDAY_24_HOUR] [varchar](1) NULL,
	[WEDNESDAY_START] [varchar](20) NULL,
	[WEDNESDAY_END] [varchar](20) NULL,
	[WEDNESDAY_CLOSE] [varchar](1) NULL,
	[THURSDAY_24_HOUR] [varchar](1) NULL,
	[THURSDAY_START] [varchar](20) NULL,
	[THURSDAY_END] [varchar](20) NULL,
	[THURSDAY_CLOSE] [varchar](1) NULL,
	[FRIDAY_24_HOUR] [varchar](1) NULL,
	[FRIDAY_START] [varchar](20) NULL,
	[FRIDAY_END] [varchar](20) NULL,
	[FRIDAY_CLOSE] [varchar](1) NULL,
	[STAURDAY_24_HOUR] [varchar](1) NULL,
	[SATURDAY_START] [varchar](20) NULL,
	[SATURDAY_END] [varchar](20) NULL,
	[SATURDAY_CLOSE] [varchar](1) NULL,
	[SUNDAY_24_HOUR] [varchar](1) NULL,
	[SUNDAY_START] [varchar](20) NULL,
	[SUNDAY_END] [varchar](20) NULL,
	[SUNDAY_CLOSE] [varchar](1) NULL,
	[SEGMENT] [varchar](20) NULL,
	[TERRITORY] [varchar](20) NULL,
	[DIVISION] [varchar](20) NULL,
	[REGION] [varchar](20) NULL,
	[TEAM] [varchar](20) NULL,
	[GROUP_ID] [varchar](20) NULL,
	[ENTITY] [varchar](20) NULL,
	[DMA] [varchar](10) NULL,
	[DMADESCRIPTION] [varchar](100) NULL,
	[FRANCHISE] [varchar](100) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL
) ON [PRIMARY]
GO

--------------------------------Create table [STG].[UM_OPS_HIEARARCHY] --------
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[UM_OPS_HIEARARCHY](
	[SETID] [varchar](10) NOT NULL,
	[C_UNIT_NO] [varchar](20) NOT NULL,
	[EFFDT] [varchar](50) NULL,
	[EFF_STATUS] [varchar](1) NULL,
	[C_UM_STATUS] [varchar](1) NULL,
	[NAME1] [varchar](100) NULL,
	[NAME2] [varchar](100) NULL,
	[NAME3] [varchar](100) NULL,
	[C_OWNER] [varchar](1) NULL,
	[C_SEGMENT] [varchar](20) NULL,
	[C_TERRITORY] [varchar](20) NULL,
	[C_DIVISION] [varchar](20) NULL,
	[C_REGION] [varchar](20) NULL,
	[C_TEAM] [varchar](20) NULL,
	[C_GROUP] [varchar](20) NULL,
	[C_ENTITY] [varchar](20) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL
) ON [PRIMARY]
GO

--------------------------- [STG].[UM_OPS_HIEARARCHY_DESCR_FILE] --------------
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[UM_OPS_HIEARARCHY_DESCR_FILE](
	[C_UM_ALIGN_KEY] [varchar](20) NOT NULL,
	[DESCR] [varchar](100) NOT NULL,
	[MANAGER] [varchar](100) NOT NULL,
	[EMAILID] [varchar](100) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL
) ON [PRIMARY]
GO


-------------[STG].[UM_ATTRIBUTES]----------------

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STG].[UM_ATTRIBUTES](
	[C_UNIT_NO] [varchar](20) NOT NULL,
	[C_LEGACY_NO] [varchar](20) NOT NULL,
	[C_TRECS_NO] [varchar](20) NULL,
	[C_DISTRIB_CENTER] [varchar](20) NULL,
	[C_POS] [varchar](20) NULL,
	[C_BOH] [varchar](20) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL
) ON [PRIMARY]
GO

----------------------[ODS].[D_STORE] -----------------------------

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ODS].[D_STORE](
	[UNIT_KEY] [int] NOT NULL,
	[UNIT_ID] [int] NOT NULL,
	[UNIT_MASTER_STATUS] [varchar](100) NULL,
	[UNIT_NAME_1] [varchar](100) NULL,
	[UNIT_NAME_2] [varchar](100) NULL,
	[UNIT_NAME_3] [varchar](100) NULL,
	[OWNER_CODE] [varchar](100) NULL,
	[ADDRESS_CONCEPT_CODE] [varchar](100) NULL,
	[ADDRESS_1] [varchar](100) NULL,
	[ADDRESS_2] [varchar](100) NULL,
	[ADDRESS_3] [varchar](100) NULL,
	[CITY] [varchar](100) NULL,
	[STATE] [varchar](100) NULL,
	[POSTAL_CODE] [varchar](100) NULL,
	[COUNTRY] [varchar](100) NULL,
	[PHONE_NUMBER] [varchar](50) NULL,
	[DMA_CODE] [varchar](10) NULL,
	[DMA_NAME] [varchar](50) NULL,
	[LONGITUDE] [varchar](100) NULL,
	[LATITUDE] [varchar](100) NULL,
	[REGION] [varchar](100) NULL,
	[DRIVE_THRU_TIMER_FLAG] [varchar](10) NULL,
	[PLAYGROUND_FLAG] [varchar](10) NULL,
	[OPEN_DATE] [datetime] NULL,
	[CLOSE_DATE] [datetime] NULL,
	[ALIGNMENT_EFFV_DT] [datetime] NULL,
	[STORE_STATUS] [varchar](5) NULL,
	[BRAND] [varchar](20) NULL,
	[SITE_TYPE_CODE] [varchar](5) NULL,
	[SUPPORTED_STORE_FLAG] [varchar](5) NULL,
	[PROG_TYPE_POLLED] [varchar](20) NULL, 
    [POS_CORP_SUPPORTED] [varchar](10) NULL,
    [POS_SUPPORT_VENDOR] [varchar](100) NULL,
    [POS_ESDM_TLOG] [varchar](10) NULL,
	[MON_IS24HR] [varchar](5) NULL,
	[MON_ISCLOSED] [varchar](5) NULL,
	[MON_STARTTIME] [varchar](20) NULL,
	[MON_ENDTIME] [varchar](20) NULL,
	[TUES_IS24HR] [varchar](5) NULL,
	[TUES_ISCLOSED] [varchar](5) NULL,
	[TUES_STARTTIME] [varchar](20) NULL,
	[TUES_ENDTIME] [varchar](20) NULL,
	[WED_IS24HR] [varchar](5) NULL,
	[WED_ISCLOSED] [varchar](5) NULL,
	[WED_STARTTIME] [varchar](20) NULL,
	[WED_ENDTIME] [varchar](20) NULL,
	[THU_IS24HR] [varchar](5) NULL,
	[THU_ISCLOSED] [varchar](5) NULL,
	[THU_STARTTIME] [varchar](20) NULL,
	[THU_ENDTIME] [varchar](20) NULL,
	[FRI_IS24HR] [varchar](5) NULL,
	[FRI_ISCLOSED] [varchar](5) NULL,
	[FRI_STARTTIME] [varchar](20) NULL,
	[FRI_ENDTIME] [varchar](20) NULL,
	[SAT_IS24HR] [varchar](5) NULL,
	[SAT_ISCLOSED] [varchar](5) NULL,
	[SAT_STARTTIME] [varchar](20) NULL,
	[SAT_ENDTIME] [varchar](20) NULL,
	[SUN_IS24HR] [varchar](5) NULL,
	[SUN_ISCLOSED] [varchar](5) NULL,
	[SUN_STARTTIME] [varchar](20) NULL,
	[SUN_ENDTIME] [varchar](20) NULL,
	[CORPORATE_SEGMENT_ID] [varchar](100) NULL,
	[CORPORATE_SEGMENT_DESC] [varchar](100) NULL,
	[CORPORATE_SEGMENT_MANAGER_NAME] [varchar](100) NULL,
	[CORPORATE_SEGMENT_MANAGER_EMAIL] [varchar](100) NULL,
	[CORPORATE_TERRITORY_ID] [varchar](100) NULL,
	[CORPORATE_TERRITORY_DESC] [varchar](100) NULL,
	[CORPORATE_TERRITORY_MANAGER_NAME] [varchar](100) NULL,
	[CORPORATE_TERRITORY_MANAGER_EMAIL] [varchar](100) NULL,
	[CORPORATE_DIVISION_ID] [varchar](100) NULL,
	[CORPORATE_DIVISION_DESC] [varchar](100) NULL,
	[CORPORATE_DIVISION_MANAGER_NAME] [varchar](100) NULL,
	[CORPORATE_DIVISION_MANAGER_EMAIL] [varchar](100) NULL,
	[CORPORATE_REGION_ID] [varchar](100) NULL,
	[CORPORATE_REGION_DESC] [varchar](100) NULL,
	[CORPORATE_REGION_MANAGER_NAME] [varchar](100) NULL,
	[CORPORATE_REGION_MANAGER_EMAIL] [varchar](100) NULL,
	[CORPORATE_TEAM_ID] [varchar](100) NULL,
	[CORPORATE_TEAM_DESC] [varchar](100) NULL,
	[CORPORATE_TEAM_MANAGER_NAME] [varchar](100) NULL,
	[CORPORATE_TEAM_MANAGER_EMAIL] [varchar](100) NULL,
	[FRANCHISE_GROUP_ID] [varchar](100) NULL,
	[FRANCHISE_GROUP_DESC] [varchar](100) NULL,
	[FRANCHISE_GROUP_MANAGER_NAME] [varchar](100) NULL,
	[FRANCHISE_GROUP_MANAGER_EMAIL] [varchar](100) NULL,
	[FRANCHISE_ENTITY_ID] [varchar](100) NULL,
	[FRANCHISE_ENTITY_DESC] [varchar](100) NULL,
	[TRECS_NUMBER] [varchar](100) NULL,
	[POS_SYSTEM] [varchar](100) NULL,
	[BOH_SYSTEM] [varchar](100) NULL,
	[DISTRIBUTION_CENTER] [varchar](100) NULL,
	[LEGACY_NUMBER] [varchar](100) NULL,
	[MD5_CHECK_SUM] [varchar](100) NULL,
	[BATCH_ID] [int] NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[CREATEDBY] [varchar](255) NOT NULL,
	[LAST_UPDATE_DT] [datetime] NOT NULL,
	[UPDATEDBY] [varchar](255) NOT NULL,
	[EFFECTIVE_DT] [datetime] NOT NULL,
	[EXPIRATION_DT] [datetime] NOT NULL,
	[CURRENT_ROW_FLAG] [varchar](5) NULL,
 CONSTRAINT [PK_D_STORE] PRIMARY KEY CLUSTERED 
(
	[UNIT_KEY] ASC,
	[UNIT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

----------------- DML SCRIPT FOR  [dbo].[Interface] ----------------------

USE [ODS-POSIntegration]
GO

INSERT INTO [dbo].[Interface]
           ([InterfaceName]
           ,[InterfaceSource]
           ,[InterfaceDestination]
           ,[DistributionList]
           ,[CreatedDate]
           ,[ModifiedDate])
     VALUES
           (
           'StoreMaster',
           'People Soft',
           'ODS', 
		   '',
           GETDATE(),
           GETDATE())
GO
--/****** Object:  StoredProcedure [STG].[UnitkeySeq]    Script Date: 6/24/2019 9:44:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [STG].[UnitkeySeq]
@Input1 INT,
@Unitkey INT OUTPUT
AS
	SELECT @Unitkey= NEXT VALUE FOR SeqUnitkey
	Return @Unitkey;
GO
------------/****** Object:  Sequence [STG].[SeqUnitkey]    Script Date: 6/24/2019 9:43:34 AM ******/
CREATE SEQUENCE [STG].[SeqUnitkey] 
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 CACHE  10 
GO
-----
/*  -- Intial Version got inserted below 
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (1, 1100014, N'O', N'CARL''S JR. 1100014', N'HEMET (W FLORIDA AVE)', N'CARL''S CORPORATE', N'C', N'JR', N'3413 W FLORIDA AVE', NULL, NULL, N'HEMET', N'CA', N'92545-3530', N'USA', N'9516523086', N'LA', N'LOS ANGELES', N'-117.00808', N'33.74723', N'CA', N'Y', N'N', NULL, NULL, CAST(N'2018-10-29T00:00:00.000' AS DateTime), N'A', N'CARL''S JR. 1100014', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'N', N'N', N'06.00.00.000000', N'23.00.00.000000', N'N', N'N', N'06.00.00.000000', N'23.00.00.000000', N'N', N'N', N'06.00.00.000000', N'23.00.00.000000', N'N', N'N', N'06.00.00.000000', N'23.00.00.000000', N'N', N'N', N'06.00.00.000000', N'00.00.00.000000', N'N', N'N', N'06.00.00.000000', N'00.00.00.000000', N'N', N'N', N'06.00.00.000000', N'23.00.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000011', N'VP WEST', N'CASSIDY, BRIAN', N'bcassidy@ckr.com', N'D0000113', N'Delgado, Enrique', N'Delgado, Enrique', N'edelgado@ckr.com', N'R0001131', N'Gonzalez, Milagros', N'Gonzalez, Milagros', N'mgonzales@ckr.com', N'T0011310', N'Gonzalez, Milagros', N'Gonzalez, Milagros', N'mgonzales@ckr.com', N'G0011310', N'CORPORATE CALIFORNIA', N'CORPORATE CALIFORNIA', NULL, N'E0011310', N'CARL''S CORPORATE', N'1052101', N'BRINK', N'CRUNCHTIME', N'DMA', N'14', N'93EB7B413CCFAA7FFE3DB0C1E7EC773D', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (2, 1100628, N'O', N'CARL''S JR. 1100628', N'SANTA ANA (N BRISTOL)', N'CARL''S CORPORATE', N'C', N'JR', N'1830 N BRISTOL ST BLDG 18', NULL, NULL, N'SANTA ANA', N'CA', N'92706-3333', N'USA', N'7148361686', N'LA', N'LOS ANGELES', N'-117.88499', N'33.76208', N'CA', N'Y', N'Y', NULL, NULL, CAST(N'2018-10-29T00:00:00.000' AS DateTime), N'A', N'CARL''S JR. 1100628', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'Y', N'N', N'23.59.00.000000', N'23.59.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000011', N'VP WEST', N'CASSIDY, BRIAN', N'bcassidy@ckr.com', N'D0000113', N'Delgado, Enrique', N'Delgado, Enrique', N'edelgado@ckr.com', N'R0001132', N'Garay, Jose', N'Garay, Jose', N'jgaray@ckr.com', N'T0011320', N'Garay, Jose', N'Garay, Jose', N'jgaray@ckr.com', N'G0011320', N'CORPORATE CALIFORNIA', N'CORPORATE CALIFORNIA', NULL, N'E0011320', N'CARL''S CORPORATE', N'1052480', N'BRINK', N'CRUNCHTIME', N'DMA', N'628', N'7431FE9B95B0F4709CBCE646EBD2F90E', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (3, 1501805, N'O', N'HARDEE''S 1501805', N'GOODLETTSVILLE', N'HARDEE''S CORPORATE', N'C', N'H', N'400 S CARTWRIGHT', NULL, NULL, N'GOODLETTSVILLE', N'TN', N'37072-1865', N'USA', N'6158591244', N'NAS', N'NASHVILLE', N'-86.70475', N'36.32168', N'MW', N'Y', N'N', NULL, NULL, CAST(N'2018-10-30T00:00:00.000' AS DateTime), N'A', N'HARDEE''S 1501805', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'23.59.00.000000', N'N', N'N', N'06.00.00.000000', N'22.00.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000012', N'VP EAST', N'Voss, Brian', N'bvoss@ckr.com', N'D0000123', N'Holloway, Dawn', N'Holloway, Dawn', N'dholloway@ckr.com', N'R0001232', N'Bozeman, James', N'Bozeman, James', N'jbozeman@ckr.com', N'T0012322', N'Sconiers, Michael', N'Sconiers, Michael', N'msconiers@ckr.com', N'G0012322', N'CORPORATE TENNESSEE', N'CORPORATE TENNESSEE', NULL, N'E0012322', N'HARDEE''S CORPORATE', N'1422105', N'BRINK', N'CRUNCHTIME', N'MBM', N'1422105', N'4E367AD9A725750AD849EBD0829B85B1', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (4, 1501809, N'O', N'HARDEE''S 1501809', N'PORTLAND', N'HARDEE''S CORPORATE', N'C', N'H', N'411 S BROADWAY ST', NULL, NULL, N'PORTLAND', N'TN', N'37148-1411', N'USA', N'6153256585', N'NAS', N'NASHVILLE', N'-86.51397', N'36.57534', N'MW', N'Y', N'N', NULL, NULL, CAST(N'2018-10-30T00:00:00.000' AS DateTime), N'A', N'HARDEE''S 1501809', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'06.00.00.000000', N'22.00.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000012', N'VP EAST', N'Voss, Brian', N'bvoss@ckr.com', N'D0000123', N'Holloway, Dawn', N'Holloway, Dawn', N'dholloway@ckr.com', N'R0001232', N'Bozeman, James', N'Bozeman, James', N'jbozeman@ckr.com', N'T0012322', N'Sconiers, Michael', N'Sconiers, Michael', N'msconiers@ckr.com', N'G0012322', N'CORPORATE TENNESSEE', N'CORPORATE TENNESSEE', NULL, N'E0012322', N'HARDEE''S CORPORATE', N'1422109', N'BRINK', N'CRUNCHTIME', N'MBM', N'1422109', N'1966CB17C66A98498BA2489EC2D40EA4', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (5, 1501821, N'O', N'HARDEE''S 1501821', N'WHITE HOUSE', N'HARDEE''S CORPORATE', N'C', N'H', N'501 HESTER DRIVE', NULL, NULL, N'WHITE HOUSE', N'TN', N'37188-9256', N'USA', N'6156725229', N'NAS', N'NASHVILLE', N'-86.67875', N'36.46763', N'MW', N'Y', N'N', NULL, NULL, CAST(N'2018-10-30T00:00:00.000' AS DateTime), N'A', N'HARDEE''S 1501821', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'06.00.00.000000', N'22.00.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000012', N'VP EAST', N'Voss, Brian', N'bvoss@ckr.com', N'D0000123', N'Holloway, Dawn', N'Holloway, Dawn', N'dholloway@ckr.com', N'R0001232', N'Bozeman, James', N'Bozeman, James', N'jbozeman@ckr.com', N'T0012322', N'Sconiers, Michael', N'Sconiers, Michael', N'msconiers@ckr.com', N'G0012322', N'CORPORATE TENNESSEE', N'CORPORATE TENNESSEE', NULL, N'E0012322', N'HARDEE''S CORPORATE', N'1422121', N'BRINK', N'CRUNCHTIME', N'MBM', N'1422121', N'8725C144D09151EA887C1378E97AA852', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (6, 1501870, N'O', N'HARDEE''S 1501870', N'MURFREESBORO #4', N'HARDEE''S CORPORATE', N'C', N'H', N'2382 OLD FORT PARKWAY', NULL, NULL, N'MURFREESBORO', N'TN', N'37128-4894', N'USA', N'6158480779', N'NAS', N'NASHVILLE', N'-86.44154', N'35.84594', N'MW', N'Y', N'N', NULL, NULL, CAST(N'2018-11-20T00:00:00.000' AS DateTime), N'A', N'HARDEE''S 1501870', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'05.00.00.000000', N'22.00.00.000000', N'N', N'N', N'06.00.00.000000', N'22.00.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000012', N'VP EAST', N'Voss, Brian', N'bvoss@ckr.com', N'D0000123', N'Holloway, Dawn', N'Holloway, Dawn', N'dholloway@ckr.com', N'R0001232', N'Bozeman, James', N'Bozeman, James', N'jbozeman@ckr.com', N'T0012325', N'Gardner, Vickie', N'Gardner, Vickie', N'vgardner@ckr.com', N'G0012325', N'CORPORATE TENNESSEE', N'CORPORATE TENNESSEE', NULL, N'E0012325', N'HARDEE''S CORPORATE', N'1422170', N'BRINK', N'CRUNCHTIME', N'MBM', N'1422170', N'A8D70D74F104F7CA08DFF6B77C144B06', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
INSERT [ODS].[D_STORE] ([UNIT_KEY], [UNIT_ID], [UNIT_MASTER_STATUS], [UNIT_NAME_1], [UNIT_NAME_2], [UNIT_NAME_3], [OWNER_CODE], [ADDRESS_CONCEPT_CODE], [ADDRESS_1], [ADDRESS_2], [ADDRESS_3], [CITY], [STATE], [POSTAL_CODE], [COUNTRY], [PHONE_NUMBER], [DMA_CODE], [DMA_NAME], [LONGITUDE], [LATITUDE], [REGION], [DRIVE_THRU_TIMER_FLAG], [PLAYGROUND_FLAG], [OPEN_DATE], [CLOSE_DATE], [ALIGNMENT_EFFV_DT], [STORE_STATUS], [BRAND], [SITE_TYPE_CODE], [SUPPORTED_STORE_FLAG], [PROG_TYPE_POLLED], [POS_CORP_SUPPORTED], [POS_SUPPORT_VENDOR], [POS_ESDM_TLOG], [MON_IS24HR], [MON_ISCLOSED], [MON_STARTTIME], [MON_ENDTIME], [TUES_IS24HR], [TUES_ISCLOSED], [TUES_STARTTIME], [TUES_ENDTIME], [WED_IS24HR], [WED_ISCLOSED], [WED_STARTTIME], [WED_ENDTIME], [THU_IS24HR], [THU_ISCLOSED], [THU_STARTTIME], [THU_ENDTIME], [FRI_IS24HR], [FRI_ISCLOSED], [FRI_STARTTIME], [FRI_ENDTIME], [SAT_IS24HR], [SAT_ISCLOSED], [SAT_STARTTIME], [SAT_ENDTIME], [SUN_IS24HR], [SUN_ISCLOSED], [SUN_STARTTIME], [SUN_ENDTIME], [CORPORATE_SEGMENT_ID], [CORPORATE_SEGMENT_DESC], [CORPORATE_SEGMENT_MANAGER_NAME], [CORPORATE_SEGMENT_MANAGER_EMAIL], [CORPORATE_TERRITORY_ID], [CORPORATE_TERRITORY_DESC], [CORPORATE_TERRITORY_MANAGER_NAME], [CORPORATE_TERRITORY_MANAGER_EMAIL], [CORPORATE_DIVISION_ID], [CORPORATE_DIVISION_DESC], [CORPORATE_DIVISION_MANAGER_NAME], [CORPORATE_DIVISION_MANAGER_EMAIL], [CORPORATE_REGION_ID], [CORPORATE_REGION_DESC], [CORPORATE_REGION_MANAGER_NAME], [CORPORATE_REGION_MANAGER_EMAIL], [CORPORATE_TEAM_ID], [CORPORATE_TEAM_DESC], [CORPORATE_TEAM_MANAGER_NAME], [CORPORATE_TEAM_MANAGER_EMAIL], [FRANCHISE_GROUP_ID], [FRANCHISE_GROUP_DESC], [FRANCHISE_GROUP_MANAGER_NAME], [FRANCHISE_GROUP_MANAGER_EMAIL], [FRANCHISE_ENTITY_ID], [FRANCHISE_ENTITY_DESC], [TRECS_NUMBER], [POS_SYSTEM], [BOH_SYSTEM], [DISTRIBUTION_CENTER], [LEGACY_NUMBER], [MD5_CHECK_SUM], [BATCH_ID], [CREATEDDATE], [CREATEDBY], [LAST_UPDATE_DT], [UPDATEDBY], [EFFECTIVE_DT], [EXPIRATION_DT], [CURRENT_ROW_FLAG]) VALUES (7, 1501823, N'O', N'HARDEE''S 1501823', N'WESTMORELAND', N'HARDEE''S CORPORATE', N'C', N'H', N'5213 HIGHWAY 31 E', NULL, NULL, N'WESTMORELAND', N'TN', N'37186-2327', N'USA', N'6156443900', N'NAS', N'NASHVILLE', N'-86.23665', N'36.55080', N'MW', N'Y', N'N', NULL, NULL, CAST(N'2018-10-30T00:00:00.000' AS DateTime), N'A', N'HARDEE''S 1501823', N'FS', NULL, N'BRINK', N'Y', N'CKE', N'Y', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'04.30.00.000000', N'22.00.00.000000', N'N', N'N', N'06.00.00.000000', N'22.00.00.000000', N'S0000001', N'COO DOMESTIC', N'BRENNAN, TOM', N'tbrennan@ckr.com', N'V0000012', N'VP EAST', N'Voss, Brian', N'bvoss@ckr.com', N'D0000123', N'Holloway, Dawn', N'Holloway, Dawn', N'dholloway@ckr.com', N'R0001232', N'Bozeman, James', N'Bozeman, James', N'jbozeman@ckr.com', N'T0012322', N'Sconiers, Michael', N'Sconiers, Michael', N'msconiers@ckr.com', N'G0012322', N'CORPORATE TENNESSEE', N'CORPORATE TENNESSEE', NULL, N'E0012322', N'HARDEE''S CORPORATE', N'1422123', N'BRINK', N'CRUNCHTIME', N'MBM', N'1422123', N'CDBB224DC79C89444CF46BCE21BEEB82', 853, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CURRENT_USER, CAST(N'2019-07-01T18:41:48.500' AS DateTime), CAST(N'9999-12-30T00:00:00.000' AS DateTime), N'Y')
*/